
  transforms:
    r_shoulder_pan_joint:     [ 0, 0, 0, 0.0, 0.0, 1.0 ]
    r_shoulder_lift_joint:     [ 0, 0, 0, 0.0, 1.0, 0.0 ]
    r_upper_arm_roll_joint:     [ 0, 0, 0, 1.0, 0.0, 0.0 ]
    r_elbow_flex_joint:     [ 0, 0, 0, 0.0, 1.0, 0.0 ]
    r_forearm_roll_joint:     [ 0, 0, 0, 1.0, 0.0, 0.0 ]
    r_wrist_flex_joint:     [ 0, 0, 0, 0.0, 1.0, 0.0 ]
    r_wrist_roll_joint:     [ 0, 0, 0, 1.0, 0.0, 0.0 ]
    head_pan_joint:     [ 0, 0, 0, 0.0, 0.0, 1.0 ]
    head_tilt_joint:     [ 0, 0, 0, 0.0, 1.0, 0.0 ]

  chains:
    arm_chain:
      gearing: [0, 0, 0, 0, 0, 0, 0]
    head_chain:
      gearing: [0, 0]

  rectified_cams:
    head_camera:
      baseline_shift: 0
      f_shift: 0
      cx_shift: 0
      cy_shift: 0

  tilting_lasers: {}

  checkerboards:
    small_cb_4x5:
      spacing_x: 0
      spacing_y: 0

